version: '3.6'

services:
  nginx:
    image: nginx:1.15.1-alpine
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - php

  php:
    image: php:7.3.2-fpm
    volumes:
      - '.:/var/www/html'
